theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/circle-opacity"  # Equinox logo in top left
    favicon: "_static/favicon.png"
    custom_dir: "docs/_overrides"  # Overriding part of the HTML

    # These additions are my own custom ones, having overridden a partial.
    twitter_bluesky_name: "@PatrickKidger"
    twitter_url: "https://twitter.com/PatrickKidger"
    bluesky_url: "https://PatrickKidger.bsky.social"

site_name: Equinox
site_description: The documentation for the Equinox software library.
site_author: Patrick Kidger
site_url: https://docs.kidger.site/equinox

repo_url: https://github.com/patrick-kidger/equinox
repo_name: patrick-kidger/equinox
edit_uri: ""

strict: true  # Don't allow warnings during the build process

extra_javascript: 
    # The below two make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "Â¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - include_exclude_files:
        include:
            - ".htaccess"
        exclude:
            - "_overrides"
            - "examples/MNIST"
            - "examples/bert_checkpoint.eqx"
    - mkdocstrings:
        handlers:
            python:
                options:
                    docstring_syle: null
                    heading_level: 4
                    inherited_members: true
                    members_order: source
                    show_if_no_docstring: true
                    show_overloads: false
                    show_root_heading: true
                    show_signature_annotations: true
                    show_source: false
                    show_symbol_type_heading: true
                    show_symbol_type_toc: true
#                 setup_commands:
#                     - import pytkdocs_tweaks
#                     - pytkdocs_tweaks.main()
#                     - import jaxtyping
#                     - jaxtyping.set_array_name_format("array")
#                     - import jax
#                     - import jax.extend.core
#                     - jax.ShapeDtypeStruct.__module__ = "jax"
#                     - jax.extend.core.ClosedJaxpr.__module__ = "jax.extend.core"

nav:
    - 'index.md'
    - 'all-of-equinox.md'
    - Examples:
        - Introductory:
            - 'examples/mnist.ipynb'
            - 'examples/train_rnn.ipynb'
        - Advanced:
            - 'examples/score_based_diffusion.ipynb'
            - 'examples/bert.ipynb'
            - 'examples/unet.ipynb'
            - 'examples/vision_transformer.ipynb'
            - 'examples/deep_convolutional_gan.ipynb'
        - Features:
            - 'examples/frozen_layer.ipynb'
            - 'examples/init_apply.ipynb'
            - 'examples/stateful.ipynb'
            - 'examples/parallelism.ipynb'
            - 'examples/serialisation.ipynb'
        - Awesome list: 'awesome-list.md'
    - Basic API:
        - Modules:
            - 'api/module/module.md'
            - 'api/module/advanced_fields.md'
        - Neural network layers:
            - 'api/nn/linear.md'
            - 'api/nn/conv.md'
            - 'api/nn/rnn.md'
            - 'api/nn/attention.md'
            - 'api/nn/activations.md'
            - 'api/nn/pool.md'
            - 'api/nn/dropout.md'
            - 'api/nn/normalisation.md'
            - 'api/nn/embedding.md'
            - 'api/nn/mlp.md'
            - 'api/nn/sequential.md'
            - 'api/nn/inference.md'
            - 'api/nn/shared.md'
            - 'api/nn/stateful.md'
        - 'api/transformations.md'
        - 'api/manipulation.md'
    - Advanced API:
        - 'api/caches.md'
        - 'api/debug.md'
        - 'api/enumerations.md'
        - 'api/errors.md'
        - 'api/pretty-printing.md'
        - 'api/serialisation.md'
    - Misc:
        - 'faq.md'
        - 'tricks.md'
        # - 'pattern.md'
        - 'citation.md'
