name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: patrick-kidger/action_update_python_project@v1
        with:
            python-version: "3.8"
            test-script: |
                cp -r ${{ github.workspace }}/tests ./tests
                python -m pip install -f ./tests/requirements.txt
                pytest
            pypi-token: ${{ secrets.pypi_token }}
            github-user: patrick-kidger
            github-token: ${{ github.token }}
            email-user: ${{ secrets.email_user }}
            email-token: ${{ secrets.email_token }}
            email-server: ${{ secrets.email_server }}
            email-target: ${{ secrets.email_target }}
